### PR TITLE
ci: Merges different platform releases into one

### PR DESCRIPTION
**Pull request by TimDeve**
This PR merges the separate releases pages into one for ease of navigation.

An example of what the release would look like can be found [here](https://github.com/TimDeve/Carp/releases/tag/merge-release), where `merge-release` would be replaced by the version tag.

### CODE REVIEW

**Comment by TimDeve** [comment]
Failure seems unrelated to the changes, Veit is describing the problem in https://github.com/carp-lang/Carp/pull/1311

**Comment by eriksvedang** [comment]
@TimDeve Oh, very nice! Thanks a ton for this!

**Review by eriksvedang — COMMENTED** [review]
Can we just as well remove the scripts in `disabled-workflows` ?

**Comment by TimDeve** [comment]
Yes, we can. I wasn't sure if you wanted to keep them or not.

**Pull request merged**
