### PR TITLE
feat: Recognize the NetBSD platform.

### PR DESCRIPTION
**Pull request by dressupgeekout**
These were the only changes I needed to make to Carp's code itself in order to get it to build and run on NetBSD/amd64 9.0.

### CODE REVIEW

**Comment by hellerve** [comment]
This looks great! Semi-related to this PR: do Github actions currently support NetBSD as a host OS? (Note: I know nothing of Github actions, so this might be a really stupid question)

**Comment by dressupgeekout** [comment]
@hellerve I honestly have no clue. My guess is no, but maybe I could look into it? I'm not that familiar with GitHub actions either.

**Comment by dressupgeekout** [comment]
Actually, now that I think about it -- even if GitHub actions did support NetBSD, it wouldn't successfully perform CI for _this_ PR, because I needed to update and/or invent several Haskell packages in the first place

**Review by hellerve — APPROVED** [review]

**Comment by hellerve** [comment]
It looks like only Windows, MacOS, and Linux are supported out of the box, but you can host your own runners? For now this doesn’t seem to be worth the effort, but good to know!

In any case, I think this PR looks fine :)

**Comment by eriksvedang** [comment]
Cool, nice addition!

**Pull request merged**
