### PR TITLE
feat: add box type

### PR DESCRIPTION
**Pull request by scolsen**
This PR adds a Box type to Carp using the initial approach in #1337. 

One important difference is that the box is implemented as a pointer, instead of a struct. While this is simpler, it doesn't play quite as well with Carp's overall programming model, since we need to treat the type specially in `TypesToC` as a result--but then again, we already do this for some other compiler defined types so it's not too strange.

### CODE REVIEW

**Comment by TimDeve** [comment]
So you've split out the implementation of Box from the recursive type implementation, correct? It looks good to me. I would maybe just add something like `Box.peek : (Fn [(Ref (Box a))] (Ref a))` so you can do things like this:

```clojure
(deftype Foo [bar Int])
(defn main []
  (let-do [b (Box.init (Foo.init 0))]
    (Foo.set-bar! (Box.peek &b) 42)
    (println* b)))
```

But I'm also ok with keeping this PR MVPish and add stuff later if we need.

**Comment by scolsen** [comment]
That's correct! I'll try to add in `Box.peek`!

**Comment by scolsen** [comment]
Ok, added `Box.peek`!

**Comment by scolsen** [comment]
The nix failure stems from a `nix-install` script failure, not from the tests.

**Comment by eriksvedang** [comment]
Very nice, let's ship it!

**Pull request merged**
