### PR TITLE
Add pointer arithmetic

### LINKED ISSUE #423: Using Carp for pointer arithmetic etc. of arrays of C structs
I’m interested in using Carp to directly and efficiently manipulate collections of C data. For example, the following C code manipulates a struct pointer to a bunch of Particles in a malloc’d buffer.  I’d like to have access to the same (C owned) buffer in my Carp code and then use Carp pointer arithmetic and dereferencing to modify any of the data.

1. Get a reference to the buffer (call out to C and get the address..)
2. Define a type to the underlying C struct (already possible)
3. Set and get values of referenced memory using Carp syntax e.g. ```(particle-ref set-x 2.5)```
4. Do pointer arithmetic on the reference (to point to any other struct in memory), e.g. ```(address-inc particle-ref)``` or ```(address-index 24 particle-ref)```

How many of these steps does Carp support currently?
What is missing?
I’m aware this may be asking a lot of Carp but it is even remotely feasible?

```
#include <stdlib.h>
#include <stdio.h>

struct Vector3 {
    float x;
    float y;
    float z;
} Vector3;

struct Particle
{
	struct Vector3 pos; // the particle’s position
	struct Vector3 vector; // the particle’s vector
} Particle;

struct Particle* p;

void dumpParticle(struct Particle *p)
{
    printf("Pos: %f %f %f\n",p->pos.x,p->pos.y,p->pos.z);
}

void main()
{
    p = malloc(1000 * sizeof(struct Particle)); // allocate memory for the collection of particles
    
    // modify the first particle
    p->pos.x = 1.0f;
    p->pos.y = 2.0f;
    p->pos.z = 3.0f;
    dumpParticle(p);
    
    p++; // point to the next particle
    p->pos.x = 4.0f;
    p->pos.y = 5.0f;
    p->pos.z = 6.0f;
    dumpParticle(p);
    
    p--; // point back to the original particle
    dumpParticle(p);
}
```

### PR DESCRIPTION
**Pull request by hellerve**
This PR tries to fix #423 by adding a few pointer functions, namely:

* `Pointer.width`:  returns the size of a pointers underlying data type,
* `Pointer.add`: adds a long integer to a pointer,
* `Pointer.inc`: increments a pointer,
* `Pointer.sub`: subtracts a long integer from a pointer, and
* `Pointer.dec`: decrements a pointer.

Test cases are included.

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
I get some errors in the tests:

```
~/Carp/out/main.c:4299:14: error: invalid operands to binary expression ('int *' and 'long')
    return p / x;
           ~ ^ ~
~/Carp/out/main.c:4312:14: error: invalid operands to binary expression ('int *' and 'long')
    return p * x;
```

**Comment by hellerve** [comment]
Sorry, I forgot to push a bunch of commits!

**Comment by eriksvedang** [comment]
Still seems to be something missing, it complains about `mul` not being defined when running `/test/pointer.carp`.

**Comment by hellerve** [comment]
Hum, I can’t reproduce that. Are you sure you’re on the newest commit (`34e1ca829c176b5a65d3d709cfcb0828ece28bf5`)?

**Comment by eriksvedang** [comment]
Sorted it out after fighting git some, sorry for bothering you.

**Comment by hellerve** [comment]
No problem, it happens :)

**Pull request merged**
