### PR TITLE
ci: Fixes scoop install as admin user

### PR DESCRIPTION
**Pull request by TimDeve**
This fixes error in Windows pipelines by [forcing the scoop installer](https://github.com/ScoopInstaller/Install#for-admin) to run.

I don't believe there is much point in not-running as Admin given the environment the CI runs in.

Edit: had to upgrade the Windows version because 2016 is getting deprecated but it comes with ASAN errors we've seen before.

### CODE REVIEW

**Comment by eriksvedang** [comment]
Looks good, but the CI still fails on Windows?

**Comment by TimDeve** [comment]
Yes this is the error I mentioned in the edit, still trying to fix it.

**Comment by eriksvedang** [comment]
@TimDeve Oh, sorry I read sloppily. Thanks for looking into it!

**Comment by TimDeve** [comment]
So I've disabled sanitize-addresses because I can't find a solution to the problem, it seems to come from the clang that comes with these newer windows version but even using our scoop's clang it doesn't work.

I believe it needs a specific combination of flags (maybe even passing the asan libs directly if some of the issues I found are to be believed) but the fact I can't reproduce locally makes it quite hard to debug.

I would merge like this as I think it's more useful to have a partially working Windows CI than none at all, I will raise an issue to track the problem and try to make a minimal CI pipeline to reproduce the issue.

**Comment by eriksvedang** [comment]
@TimDeve Sounds good, thanks again!

**Pull request merged**
