### PR TITLE
Add some const qualifiers, removed MALLOC() null checks, fixed Float_…

### PR DESCRIPTION
**Pull request by jacereda**
…modf(), use memcpy() instead of memmove().

### CODE REVIEW

**Comment by jacereda** [comment]
I guess removing the NULL checks might be controversial. The rationale is that it's never checked in lots of other places, it adds a lot of noise to static analysis and we have tons of memory.

**Comment by hellerve** [comment]
I’d just like to object to:

> and we have tons of memory

Carp has been used to do work on Eurorack modules that have 16k of RAM + 32k of memory ([these guys](https://www.st.com/en/microcontrollers-microprocessors/stm32f301.html)). There, `malloc` might fail relatively easily; at this rate, returning `NULL` might be our best option. Ideally, I’d opt for fixing the places where it isn’t checked, even if it’s more work.

**Comment by jacereda** [comment]
I've done some embedded programming and in those cases the best thing to do is not to allocate at all and work with static buffers. And I always prefer a crash at the right place than hiding the bug and crashing later.

But in any case, I guess this could be wrapped in a CHECKED_MALLOC() macro for most uses. That could be another PR.

**Comment by hellerve** [comment]
(Adding @trentgill to this conversation in case he has opinions about this)

`CARP_MALLOC` is already a macro, so maybe redefining it to be checked if desirable might be interesting.

Crashing early is great, but undefined behaviour usually isn’t. I’d understand calling `abort()` et al. if allocation fails, but moving on and trying to invoke `memcpy` makes me a little unhappy—I know we do it in other places because of oversights and/or laziness, but that shouldn’t be an excuse. Would you be open to that instead or is there anything that speaks against that?

**Comment by hellerve** [comment]
Bottom line: I’m okay with us merging this, and I’d like to contribute a checked version of malloc unless you want to. Is that okay?

**Comment by trentgill** [comment]
No objections from me. I always add the NULL checks in my programs, but usually out-of-mem issues are found intuitively. Having to pass the failure back through the call stack usually means it never happens anyway.

**Comment by hellerve** [comment]
Cool, so I think we have an agreement on your approach, @jacereda!

**Pull request merged**
