### PR TITLE
New evaluator

### PR DESCRIPTION
**Pull request by hellerve**
This PR is meant to track the progress of rewriting the evaluator. Currently this is very much a work in progress and pretty messy, but it will get better I’m sure.

### Goals

The goals of this evaluator are to move away from an ad-hoc, not very well defined evaluator to a well defined, simple, but extensible version. The evaluator should be specified using a design document.

While we’re at it, we should also resolve some long-standing issues with the old evaluator.

We want to fix the following issues at least (let me know if I missed any):
- #555 
- #673
- #659

### Implementation

This implementation adds multiple changes to the IR as well as to the evaluator.

#### IR

We add a `Closure` type that wraps dynamic functions et al with their environment to add lexical scoping. This solves the weird dynamic-scoping problems that we occasionally had before.

#### Evaluator

The evaluator moves towards extensibility by adding primitives as well as commands. One gets evaluated arguments, while the other one does not. This means that special commands such as `def*`, `type`, `info`, etc. can be expressed as functions instead of having to be part of the evaluator loop. This makes it easier to extend the set of commands and reduces the amount of  duplicated work.

We also move away from double evaluation in the REPL (which was extremely error-prone) to recursive macro expansion (still a WIP), which is a little more standard and well-understood.

### State

Currently, I estimate that about 2/3 of the production work are done, after which we’ll have to clean up the code, reorganize it, and finally test it.

An itemized todo list:
- [x] Refactor evluator loop
- [x] Add primitives
- [x] Add `Closure`
  - [x] Make sure closures are unwrapped properly everywhere (especially in the emitter and qualifier)
- [x] Get to feature parity of evaluator loop
- [x] Add argument capability to commands
- [x] Recursively expand macros
- [x] Add  evaluator tracebacks
- [x] Make REPL autocomplete update with every loop
- [x] Clean up
- [ ] Validate

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
First of all – great job! This is truly awesome and so much better than what was before.
Here's some feedback after trying it out (I've lettered them to make it easier to respond to a specific one:

- [A] When the top-level result is Unit (empty list) it shouldn't be printed.

- [B] Pasting a whole code block (with multiple top-level forms) into the repl doesn't work (only the first one is evaluated). I prefer if they all print their results (except if it's Unit).

- [C] Entering a symbol at the top level should (probably) just echo the name and it's type (using 'showBinderIndented' or something like that).

- [D] Situation 3 does not give the expected result, calling 'foo' should evaluate to () and define 'a' to be 3.5 but instead it returns (if true (def a 3.5) (def a 10)). Wrapping foo in an extra set of parens leads to infinite loop in the repl, it seems.

- [E] Situation 4 did not do what I expected, defining f leads to no output while calling it with (f) gives both outputs. Perhaps this is correct though, I'm not sure...

- [F] Situation 5 didn't do what I expected, (m true 'AHA 'BOO) returns (if x b a), but perhaps that's exactly what it SHOULD do?

- [G] Would be nice to also be able to use :i as a shortcut for (info <symbol>), now that :t works!

- [H] This is more of an open-ended question: How hard is it do get back the behaviour (but in a principled way) of being able to call static functions from the repl? Right now calling (defn f [] 123) at the repl like so: (f) returns ((defn f [] 123)) which is bewildering. There is (or were) a Haskell function called 'executeFunctionAsMain' for doing this call more or less intelligently (redefining main to call the function, execute the program, and then restore main to what it was before). Ideally this would work for global variables too. It's a whole can of worms but I think it's something everyone wants and I had started to rely a bit on it already, despite it's buginess in the old Eval.

**Comment by hellerve** [comment]
Thank you for the kind words and the feedback @eriksvedang, much appreciated! I’ll address the easy concerns first:

[A], [C], [G], and [H] should now be fixed. Commit 60e4d337 showcases how easy adding a new REPL shortcut is now.

[B] will be fixed soon.

I’ll go through [D-F], which are concerned with the examples you defined in #697 (thanks again for that) in a follow-up comment.

**Comment by hellerve** [comment]
D) and E) boil down to the same question: should dynamic functions expand macros on definition or should they “interoperate”? Last we talked I think we decided the only difference between dynamic functions and macros should be that macros do not evaluate their arguments. We can change that to macros expanding in-place in dynamic functions, which would enable a different kind of interoperation. Let’s talk about this in more depth next time we meet?

About [F]: I think this should be fixed, because this is definitely not how other macro systems work. I’ll look at it sometime this week.

**Comment by eriksvedang** [comment]
Sweet! Yes, adding `:i` was quite easy indeed :)

**Comment by hellerve** [comment]
Since some time has passed since the last update in here, I decided it might be time to write up what has happened.

I decided to take on #696 as part of this work as well, which has proved harder than expected. I’ve found the general problem—`do` reused the old context for all statements inside it, and `StateT` was too lazy for us. I fixed the first problem, and am mostly done with rewriting from a `StateT` to explicit context-passing. So far, so good.

However, it turns out that fixing `StateT` required me to think about how to fix [F], and I realized that there is a fundamental flaw in how we think about macro expansion. Let me elaborate.

Consider this macro from `core/Macros.carp`:

```clojure
(defmacro and [x y]
  (list 'if x y false))
```

Now imagine we use it like this:

```clojure
(defn between [x l u]
  (and (>= x l) (<= x u)))
```

This will first expand to:

```clojure
(defn between [x l u]
  (if (>= x l) (<= x u) false))
```

but the evaluator cannot determine whether it is done, because `if` exists both at compile time and at run time. It will thus try to expand it once again, and fail.

Why does it have to evaluate again? Because some macros generate macros, and we have to account for those. We have to recurse. It turns out that the double evaluation was a problem from the get-go, but now that I’m rewriting the evaluator for the—second? third?—time and doing it properly I realize that its repercussions run deeper than I first understood.

The “obvious” solution would be to separate between the evaluator and the "meta langauge" (defining types etc.), but this would require yet another rewrite, and U’m not quite sure whether this would lead me anywhere where I would care to be.

If anyone has any input, that’d be great. I’m pretty stumped right now (and I dont understand why this has not lead to problems earlier). My current working theory is that there is a fundamental incapability to express what we want to express in the last few examples of #697 without a more principled separation of concerns at compile time.

Maybe I’m also just talking nonsense, I’ve been staring at macro expansion for a very long time.

My interim work for rewriting state handling can be inspected in [my branch `where-is-this-going`](https://github.com/hellerve/Carp/tree/where-is-this-going), which is an apt name for my current state of mind.

Cheers

**Comment by hellerve** [comment]
I’ve already shared this information in the Gitter channel, but the rewrite seems to work now! We are ready for a code review while I will go ahead and write some documentation. This will probably still take a minute, since there is a lot that could possibly be written about! I’ll try to keep it manageable though.

**Comment by eriksvedang** [comment]
Awesome work.

**Pull request merged**
