### PR TITLE
[DO NOT MERGE] Make range a regular function

### PR DESCRIPTION
**Pull request by hellerve**
This PR rewrites range to be a regular function. This solves a todo in `docs/Todo.md`.

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
Great, so nice to get rid of these things in the compiler!
I think the new implementation is a bit too prone to infinite loops though, for example this:
```(Array.range 1 100 2)``` since it "misses" the end condition.

**Comment by hellerve** [comment]
Right. We’ll have to check whether `start` or `end` are smaller and then use the appropriate check.

**Comment by hellerve** [comment]
`range`, too, could benefit from a way of statically allocating an array, by the way.

**Comment by hellerve** [comment]
I added a commit that gets the correct function. However, that exposed a compiler bug. The compiler emits the type `Fn__int_int_bool`, but does not emit a definition of that type.

**Comment by eriksvedang** [comment]
Pushed a fix now, hope it helps.

**Comment by hellerve** [comment]
I rebased and ran the tests; it seems to work now! I added two regression test cases as well.

**Pull request merged**
