### PR TITLE
Echoes examples path when running run_carp_tests.sh

### PR DESCRIPTION
**Pull request by TimDeve**
Makes it easier to see which file failed in case of errors.

### CODE REVIEW

**Comment by TimDeve** [comment]
The Windows failure seems to be caused by [526a5c157](https://github.com/carp-lang/Carp/commit/526a5c1573dc1d94a499ad37a3b1d11c86cd9b84).

**Comment by jacereda** [comment]
Regarding the build failure, I think it would be better to leave the responsibility of generating a shared library to the user.  We could pass `/LD` for `clang-cl`, but that's just the beginning. Do we want to maintain a flags list for the dozens of C compilers out there? I think setting the compiler flags via `Project` is more than acceptable.

**Comment by eriksvedang** [comment]
> I think setting the compiler flags via Project is more than acceptable.

Yeah, that makes a lot of sense – lets do that instead.

**Comment by eriksvedang** [comment]
Nice!

**Pull request merged**
