### PR TITLE
feat: Implicit struct init

### PR DESCRIPTION
**Pull request by eriksvedang**
Closes https://github.com/carp-lang/Carp/issues/753.

Example of what you can do:

```clojure
(defmodule Wrap
  (deftype A [x Int y Int]))

(use Wrap)

(A 3 4)
```

(no `.init`)

### CODE REVIEW

**Comment by eriksvedang** [comment]
This also fixes a bug where deftypes (including sumtypes) would get the global environment as their parent env. Possibly this leads to fixing some old bug regarding lookup..!

**Review by jacereda — APPROVED** [review]
Nice!

**Comment by scolsen** [comment]
> This also fixes a bug where deftypes (including sumtypes) would get the global environment as their parent env. Possibly this leads to fixing some old bug regarding lookup..!

ohhh sweet--that will maybe (?) fix a lot of issues with submodules too

**Comment by scolsen** [comment]
Also seems like this fixes #930 based on the test

**Pull request merged**
