### PR TITLE
Use unlines instead of joinWith.

### PR DESCRIPTION
**Pull request by jacereda**
Just a cosmetic change.

### CODE REVIEW

**Comment by hellerve** [comment]
The failing tests look like there is an extra empty line inserted somewhere by the compiler now; is that possible?

**Comment by jacereda** [comment]
Yes, I probably messed it in some place, let me check.

**Comment by scolsen** [comment]
Ahh yeah, `unlines` appends an `\n` after the final item in the list, while `joinWith` uses `intercalate` which doesn't.

**Comment by jacereda** [comment]
Oh, right, too many hours in front of a computer today :)

**Comment by scolsen** [comment]
> Oh, right, too many hours in front of a computer today :)

I like the general idea though--maybe we can replace `joinWith "\n"` by a new function partially applied to `\n`:

```
joinLines :: [[a]] -> [a]
joinLines = joinWith "\n"
```

**Pull request closed without merging**
