### PR TITLE
Only allow Int as return type for main

### PR DESCRIPTION
**Pull request by jacereda**
With this change the test suite passes using `tcc` as the compiler.

Sits on top of #869.

### CODE REVIEW

**Comment by hellerve** [comment]
I’ll have to change a bunch of my libraries, but I think this change is worth it if it means standard-compliance.

**Comment by bjorn3** [comment]
Maybe make Carp add an implicit `return 0;` instead?

**Comment by jacereda** [comment]
I prefer explicit behaviour, and sticking to standard C conventions, but I'm not opposed to having `main` return unit.

Making `main` return 0 implicitly would imply requiring an `exit` call to return an error from an executable. Some people have aversion to having several exit points in a program.

**Comment by hellerve** [comment]
I don’t think implicit behavior is usually a good thing. If we find that it’s too much, we can also add a macro that just appends `0` to the body.

**Comment by eriksvedang** [comment]
I don't think returning Unit really counts as "implicit", it seems like a pretty good indication that you're not interested in reading the return value from the executable after it has run, no?

Why not make main return an int when its type is `(Fn [] Int)` and return 0 when its type is `(Fn [] ())`? This seems to strike a balance between standard compliance and practicality.

**Comment by eriksvedang** [comment]
We can close this now that #881 is merged, right?

**Pull request closed without merging**
