### PR TITLE
Bug #343 Fixing off-by-one in Heap parent function.

### PR DESCRIPTION
**Pull request by chrisosaurus**
Adding more comprehensive tests for Heaps to prevent happening again..

### CODE REVIEW

**Comment by hellerve** [comment]
Is it possible for `(- i 1)` to be `< 0`?

**Comment by opqdonut** [comment]
@hellerve yeah, if somebody tries to find the parent of the root (i=0)

How about adding some tests that check `(= i (parent (lchild i)))` and `(= i (parent (rchild i)))`? The current tests are fine but that's the exact thing that was broken, right?

**Comment by chrisosaurus** [comment]
I is only meant to be an array index, and my code only calls it for I >=1
Even if you call it with I = 0 then (/ (- I )1 2) should still be 0


@opqdonut I constructed the new tests by going through how a heap should work on paper at each step, and then codifying the interesting cases that the previous implementation missed (that our tests didn’t cover).

We can always add more tests, even as follow up prs. I don’t have access to a machine where I can code, I can add some more tomorrow morning.
You’re also welcome to send prs for more tests, the carp tests are generally quite light and are more smoke tests than in-depth tests.


I was thinking of trying to write a fuzzer, or exposing another sort (even just qsort) - that way we could just generate large random sequences and check that our sort matches the other implemention(s).
I might try write a quick sort in carp, and then re-add a qsort wrapper, then we can let the user pick which they want and we can test that they all have the same output for large semi random inputs.

**Comment by opqdonut** [comment]
Yeah I'm definitely not against merging this, just thinking out loud.

**Comment by eriksvedang** [comment]
Thanks for the quick fix, @chrisosaurus!

**Comment by chrisosaurus** [comment]
@opqdonut oh don't get me wrong, I think it is a good idea to add more testing both here and to wider Carp. I suspect your AoC is probably the most complex body of code we currently have in Carp!

**Pull request merged**
