### PR TITLE
Linux fixes

### PR DESCRIPTION
**Pull request by jacereda**
This fixes the problems I encountered when compiling under NixOS while preparing a fix for #708 .

### CODE REVIEW

**Comment by hellerve** [comment]
This looks good to me, although it is mildly flabbergasting that adding `U` to our characters, i.e. emitting `char32_t` didn’t lead to more errors. One thing that definitely breaks is `chars` and `from-chars`:

```clojure
  (assert-equal test
                &[\s \v \e \d \ä \n \g]
                &(chars "svedäng")
                "chars works as expected")
  (assert-equal test
                "svedäng"
                &(from-chars &[\s \v \e \d \ä \n \g])
                "from-chars works as expected")
```

Both of these test cases would currently fail.

(BTW: I had to look up what type the `U` character literal emits and decided to take a look at the C standard; it seems that C99 only had `L` character literals and `u` and `U` were added in C11.)

**Comment by jacereda** [comment]
Yes, those tests would be handled in the next PR (unless those were already passing).
As for `U` being C11, AFAIK (correct me if I'm wrong) it's quite widespread even in pre-C11 compilers, but we can always replace those by the numeric value at some point if it's problematic.

**Comment by hellerve** [comment]
I think it should be fine, but I’m personally also lucky enough to have a quite simple setup (modern compilers, almost no constraints).

I just made up those tests because I was interested in whether it would be somehow handled magically, expecting them to fail. When we make the switch to `U`, though, I guess they should be made to pass.

Was the `U` change a first stab at #708 or is that part of making it work on Linux?

**Comment by jacereda** [comment]
The `U` change was just the simple side of #708, mainly making `str` work on wide characters.

**Comment by hellerve** [comment]
Cool. I’m happy with keeping it in this PR, just wanted to clarify.

**Comment by eriksvedang** [comment]
Is this PR surpassed now? @jacereda

**Comment by jacereda** [comment]
Sure.

**Pull request closed without merging**
