### PR TITLE
Moves scripts in scripts folder

### PR DESCRIPTION
**Pull request by TimDeve**
Would close issue #851, should I put the nix files in their own folders as well? I'm not sure who depends on them.

### CODE REVIEW

**Comment by TimDeve** [comment]
Kind of a separate topic but should we have `(Debug.sanitize-addresses)` in the benchmarks? Doesn't that make them slower? Or does it just use more memory?

**Comment by hellerve** [comment]
I think @jacereda introduced the nix files.

**Comment by hellerve** [comment]
Also, I would guess that it does make them slower.

**Comment by jacereda** [comment]
What's the proposal? Moving nix stuff to `scripts` as well or move it to another directory? If it's another directory, I could just combine both .nix scripts into a single `default.nix` file. The main directory pollution would be a single file vs a single directory, so I guess it wouldn't be worth it. 

If we want those in the `scripts` directory it should be fine albeit a bit more cumbersome, since entering an environment would no longer be a `nix-shell` from the carp directory, it would require specifying the path to `shell.nix`. Not a big problem though.

Feel free to move them and I'll PR again with whatever fixes are required to make it work again on Nixpkgs.

**Comment by eriksvedang** [comment]
`(Debug.sanitize-addresses)` has found a lot of bugs so far, so I don't think we should remove them...

**Comment by TimDeve** [comment]
@jacereda I meant in their own folder, you're right if it's possible to merge them it would achieve the same outcome.

**Comment by eriksvedang** [comment]
@TimDeve Oh, sorry I missed that you wrote *benchmarks*. Yeah lets remove it from there!

**Comment by scolsen** [comment]
So glad the macOS CI is fixed!

**Pull request merged**
