### PR TITLE
fix: expand macros in closure bodies

### PR DESCRIPTION
**Pull request by hellerve**
This PR fixes a problem where previously, macros where not expanded inside dynamic closures.

Cheers

### CODE REVIEW

**Review by scolsen — APPROVED** [review]

**Comment by scolsen** [comment]
Great!

**Comment by eriksvedang** [comment]
Nice fix. I'm a little suspicious of it though, since we don't call `macroExpand` in any other place except in macros – so maybe this fix should actually be in the function `macroExpand`, where we *do* match on a bunch of different things? I might just be misguided, let me know in that case!

**Comment by hellerve** [comment]
We actually do call `macroExpand for all `def` forms in `dynamicOrMacro` and for `defmodule` directly in `step`, i.e. on definition time. Since `fn` goes through neither definition form, it doesn’t get the same treatment. Does that make sense?

**Comment by eriksvedang** [comment]
OK, thanks for the clarification. I'll look at it once more when not tired but seems legit!

**Pull request merged**
