### PR TITLE
Renaming: String.count -> String.length, Array.count -> Array.length

### PR DESCRIPTION
**Pull request by mkfifo**
Issue #236

The next steps would be to change count-char to just count

### CODE REVIEW

**Comment by eriksvedang** [comment]
Yes, this is a good idea! I'll merge it when it has no conflicts.

**Comment by mkfifo** [comment]
@eriksvedang thanks! rebased now to remove conflicts, and all tests are passing \o/

It's so nice having all those tests.

**Comment by eriksvedang** [comment]
Will merge when the new conflicts are solved!

**Comment by mkfifo** [comment]
@eriksvedang thanks, all conflicts fixed. There isn't much we can do here, since we are touching the same areas in the same files across multiple PRs, it isn't a big problem.
I also included documentation changes as a separate commit.

**Pull request merged**
