### PR TITLE
Address unused matches.

### PR DESCRIPTION
**Pull request by jacereda**
This one could be controversial. For one, it might help locate bugs. On the other hand, it can make some parts a bit more obscure.

### CODE REVIEW

**Comment by jacereda** [comment]
Somehow I managed to break Haskell's "if it compiles it works" here. Let me check...

**Comment by jacereda** [comment]
And I messed it in a place that would be caught by `-Wname-shadowing` :)

**Comment by scolsen** [comment]
> Somehow I managed to break Haskell's "if it compiles it works" here. Let me check...

Weird that it typechecked--I'm guessing a variable in a larger scope of the same type shadowed one of the removed names?

**Comment by scolsen** [comment]
> And I messed it in a place that would be caught by `-Wname-shadowing` :)

We probably should turn that on--I have a feeling there's probably a lot of cases of this since we have so many local definitions

**Review by eriksvedang — APPROVED** [review]
Awesome!

**Comment by eriksvedang** [comment]
Needs rebase.

**Comment by jacereda** [comment]
Rebased.

**Pull request merged**
