### PR TITLE
core: add Phantom

### PR DESCRIPTION
**Pull request by hellerve**
This PR adds `Phantom` to core, which is a type that has no inhabitants but a type variable. They enable us to express type level constraints in code. Consider the example I added to the tests.

```clojure
(defn m [a] (Phantom.ensure a (the (Phantom Int) (Phantom.init))))

(println* (m 123l))
```

This will not unify, since `m` is passed a `Long`, not an `Int`, as required by the phantom. Wait, but don’t we already have `sig` and `the` to express such constraints? Yes, but Phantom types can be passed around like data, making those `ensure`s more expressive.

They also exist [in Rust](https://doc.rust-lang.org/std/marker/struct.PhantomData.html), for borrow-checking purposes, and we could add that sort of functionality if we ever add lifetime annotations, but for now they are useful as is.

Cheers

### CODE REVIEW

**Comment by scolsen** [comment]
Woo, awesome! My only comment is that we should add a `doc` for `ensure` and probably for `Phantom` too, since beginners may not be familiar with this type-level super power. I think we can do that in a follow-up PR though.

**Comment by hellerve** [comment]
I added docs for `Phantom`, I hope they make sense. I have trouble communicating why this is interesting in a clear, beginner-friendly manner.

**Comment by scolsen** [comment]
> I added docs for `Phantom`, I hope they make sense. I have trouble communicating why this is interesting in a clear, beginner-friendly manner.

I think it's actually very clear!

**Comment by eriksvedang** [comment]
Very cool!

**Pull request merged**
