### PR TITLE
chore: Creates git hook to enforce Conventional Commits

### PR DESCRIPTION
**Pull request by TimDeve**
Creates git hook to enforce Conventional Commits as well as a shell script to setup the git hook.

Mentions the setup script in the Contributing doc.

### CODE REVIEW

**Comment by TimDeve** [comment]
Sorry didn't realise I pulled in commits from the other PR.

**Comment by jacereda** [comment]
Isn't it simpler to just add .git/hooks to the repo?

**Comment by TimDeve** [comment]
I've never seen it done that way, is that possible?

**Comment by eriksvedang** [comment]
What will happen when this is merged, seems like we need something in the workflows too right?

**Comment by TimDeve** [comment]
Do you mean something to enforce it in the CI? in my experience the git hook is enough.

**Comment by eriksvedang** [comment]
> Do you mean something to enforce it in the CI? in my experience the git hook is enough.
> 
> People need to setup the hook and then it'll stop the commit if it doesn't conform.

Ah, I didn't know that's how it works. Cool.

**Comment by TimDeve** [comment]
@carp-lang/maintainers If you don't mind running `scripts/setup-git-hooks.sh` next time you pull master.

**Comment by hellerve** [comment]
I get this message when committing now (making me unable to commit with the script):

```
awk: illegal primary in regular expression ^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?(!|)?: .* at ?: .*
 source line number 1
 context is
	/^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?(!|)?: >>>  .*/ <<<
```

**Comment by TimDeve** [comment]
Argh, sorry. 
Could you tell me what you get when you run `/bin/sh -c 'echo $SHELL'`? 
Meanwhile you can ` rm .git/hooks/commit-msg` to avoid the problem.

**Comment by TimDeve** [comment]
Never-mind it seems I have the opposite problem I thought I would get: my awk is gnu awk rather than the MacOS one, will fix it this evening.

**Comment by TimDeve** [comment]
Sorry about that, this should fix it: https://github.com/carp-lang/Carp/pull/1042

**Comment by scolsen** [comment]
Leave it to `awk` to make for script `awk`wardness...

**Comment by TimDeve** [comment]
Ahahah 😂

Not sure if I should enable you...

**Pull request merged**
