### PR TITLE
Compile with link-time optimizations, use standard NDEBUG instead of …

### PR DESCRIPTION
**Pull request by jacereda**
…OPTIMIZE.

### CODE REVIEW

**Comment by jacereda** [comment]
The NDEBUG bit should make it easier to integrate with other projects.

The LTO part makes executables smaller by stripping unneeded symbols.

**Comment by hellerve** [comment]
I think getting rid of `OPTIMIZE` is a good idea.

Abou the other C flag: were you aware that `(add-cflag "-flto")` would also be possible? Maybe that would be a better idea, so that people that don’t want this optimization for whatever reason can leave that out?

**Comment by jacereda** [comment]
Right, removed the LTO flag.

**Comment by eriksvedang** [comment]
Excellent, thanks!

**Pull request merged**
