### PR TITLE
make bit-* interfaces

### PR DESCRIPTION
**Pull request by hellerve**
This PR makes bitwise operations interfaces.

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
Great! I think you have to use Fn instead of the lambda literals for it to work on Windows..? (On my phone so I didn’t investigate this)

**Comment by hellerve** [comment]
Since the other interfaces also use lambda and the Windows tests pass I‘d argue we‘re good?

**Comment by eriksvedang** [comment]
@hellerve OK, yeah...

**Comment by hellerve** [comment]
I think the problem is the rendering, not the source files? I can’t quite remember the issue, TBH.

**Pull request merged**
