### PR TITLE
Long type to ensure longs are actually 64 bits.

### PR DESCRIPTION
**Pull request by jacereda**
Plain `long` is 32 bits on some platforms (most notably Windows). Code like the following fails on those:

```
long Double_to_MINUS_bytes(double x) {
    long y;
    memcpy(&y, &x, sizeof(double));
    return y;
}
```

### CODE REVIEW

**Comment by hellerve** [comment]
It’d be great if we could have this in core! It’s been open for a while, what’s holding it back?

**Comment by eriksvedang** [comment]
Hmm, not sure. I'm open to merge:ing it as-is but it needs a rebase.

**Comment by hellerve** [comment]
Since this seems to be the only thing preventing a passing Windows CI build, I’d be happy to take this over if you want to hand it over, @jacereda! If you’d like to rebase yourself, though, that’s of course also totally okay.

**Comment by eriksvedang** [comment]
Yes please!

**Comment by eriksvedang** [comment]
This is fixed now.

**Pull request closed without merging**
