### PR TITLE
Remove shell.nix.

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by jacereda** [comment]
As discussed in #955, this should clean up a bit more the project root.

**Comment by eriksvedang** [comment]
Sweet!

**Comment by jacereda** [comment]
I want to add a workflow for building on Linux+Nixpkgs. Should I just add the file to .workflows and PR? Is that enough to test if it will build?

**Comment by jacereda** [comment]
Nevermind, looks like PRing is enough.

**Pull request merged**
