### PR TITLE
Sdl unused

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by eriksvedang** [comment]
What do you mean with it being unused?

**Comment by jacereda** [comment]
`SDL_INIT_EVERYTHING` is just a XOR of all the initializable subsystems. As is, it isn't doing anything.

**Comment by jacereda** [comment]
It would be useful if the library provided `SDL_Init()`.

**Comment by eriksvedang** [comment]
Oh, OK :)

**Comment by eriksvedang** [comment]
It does wrap `SDL_init` though.

**Comment by jacereda** [comment]
Oh, I missed that. I’ll fix it later. Should it wrap the individual values or just the EVERYTHING?

**Pull request merged**
