### PR TITLE
Add open-file function

### PR DESCRIPTION
**Pull request by sdilts**
`fopen` returns a nullable pointer, which doesn't fit very well with Carp's notions of saftey and error handling. Add the function `open-file` that returns a `Result` type that forces the user to check if the operation was successful.

Partial fix for #617

### CODE REVIEW

**Comment by jacereda** [comment]
Wouldn't it be better to return `(Result Int (Ptr FILE))`, with the `Int` part being the `errno`?

**Comment by sdilts** [comment]
That would make a lot more sense.

**Comment by hellerve** [comment]
Could we add a test to the test suite while we’re at it?

**Comment by sdilts** [comment]
Not sure what the tests need to be since we are just testing a wrapper for a system function, but I think these are enough. Is there anything else I should add?

**Comment by hellerve** [comment]
No, that looks great to me now!

**Comment by eriksvedang** [comment]
Very nice!

**Pull request merged**
