### PR TITLE
Issue #252 Heapsort

### PR DESCRIPTION
**Pull request by mkfifo**
This adds
  Array.push-back!
  Array.pop-back!
  Heap modules including Heap (generic), MaxHeap, MinHeap, and HeapSort
  Sort module including in place sort and external sort

This adds tests for all of the above and
  Array.push-back
  Array.pop-back

This subumes the previous PR #261

### CODE REVIEW

**Comment by eriksvedang** [comment]
Very nice! Code looks great. My one piece of feedback before merge:ing is to move the `(use Heap)` statement inside the `Sort` module to not effect global scope. Cheers

**Comment by mkfifo** [comment]
@eriksvedang I don't think that use is needed, I was unsure, but testing shows it isn't needed - I presume because Heap is within Core

fixed.

**Comment by mkfifo** [comment]
Please hold off on merging this I just want to tidy up the interface a little bit to more closely match the current sort

I'll let you know when I think it is ready to be merged

**Comment by mkfifo** [comment]
so now we have 

sort! &arr -> unit (in place mutable)
sort arr -> arr (in place ownership)
sorted &aa -> arr (makes copy and then sorted in copy)

I still want to add some -with-cmp or -with-ord versions for custom sorts

**Comment by mkfifo** [comment]
The -with-cmp and -with-ord versions will be much cleaner once we have closures, so I might leave them until then.

The only place this matters is if you want to sort an array with a non-default ordering, but that is awkward to do without closures anyway.

This is ready to merge

**Comment by mkfifo** [comment]
Now testing sorting of arrays for strings/ints/floats/chars

**Comment by eriksvedang** [comment]
Sorry for being obnoxious but do we really need the Sort module now? It won't help when we add `sort` functions for other types, right? I'm definitely happy to merge this as-is but now there will be code that uses Array.sort and some code that uses Sort.sort which seems unnecessarily messy. 

If you want to add  `sort`/`sorted` interfaces in Interfaces.carp already, that's also fine by me.

**Comment by mkfifo** [comment]
@eriksvedang not obnoxious at all :)

**Pull request merged**
