### PR TITLE
Adds a FreeBSD 12.x CI target using builds.sr.ht

### PR DESCRIPTION
**Pull request by dbalan**
This job needs configuring at sr.ht platform (this needs to done by the github repo owner)

1. Sign up for sourcehut.org
2. Add triggers
 - for commit building: https://dispatch.sr.ht/github_commit_to_build/configure
 - for building PRs: https://dispatch.sr.ht/github_pr_to_build/configure

Related to #796

### CODE REVIEW

**Comment by hellerve** [comment]
@eriksvedang this looks like a job for our BDFL!

**Comment by eriksvedang** [comment]
I don’t think I’ll have time/energy to support this, sorry.

**Comment by jacereda** [comment]
I'd like to see this happen. Maybe it doesn't need to be the repo owner and an organization member would suffice.

**Comment by jacereda** [comment]
I do care about BSDs, but I'm also interested in ARM platforms:

https://man.sr.ht/builds.sr.ht/compatibility.md

**Comment by hellerve** [comment]
SImilarly, I think it’s important to test the platform if it’s in the list of supported platforms (which it is, as of #796).

Sadly, these things are currently limited in the sense that Erik is the only person who is in the GitHub organization, so it stands and falls with his approval.

**Comment by eriksvedang** [comment]
Sure, I'm up for finding a solution to this. 

> SImilarly, I think it’s important to test the platform if it’s in the list of supported platforms (which it is, as of #796).

Agreed.

I can add @hellerve or @jacereda as I trust that you're invested in the future of Carp. I will retain the sole right to merge PR:s though. Is this a possible setup?

**Comment by jacereda** [comment]
> Sure, I'm up for finding a solution to this.
> 
> > SImilarly, I think it’s important to test the platform if it’s in the list of supported platforms (which it is, as of #796).
> 
> Agreed.
> 
> I can add @hellerve or @jacereda as I trust that you're invested in the future of Carp. I will retain the sole right to merge PR:s though. Is this a possible setup?

Sure, no problem.

**Comment by hellerve** [comment]
Yeah, that’s fine with me as well. I don’t know whether the sr.ht setup will work then, but I think having more than one person in the org sounds like a good way moving forward.

**Comment by eriksvedang** [comment]
OK, reopening it then :)

Sorry about that @dbalan, didn't want to be negative but I'm wary of things that steal time from more pressing issues with the language.

I'll look into adding people to the org.

**Comment by hellerve** [comment]
It doesn’t look like being an organization member is enough. Dang.

**Comment by jacereda** [comment]
I'm not sure, have you tried clicking the 'Request' button in the organization? I guess Erik will receive a permission request and maybe from then on we can proceed.

**Comment by dbalan** [comment]
@eriksvedang No worries.

FWIW I have setup a nightly build of carp repositories on builds.sr.ht and email me on failure. Its a bit hard to expose any sort of build status page with the way this job is setup :(

**Comment by eriksvedang** [comment]
Access granted.

**Comment by hellerve** [comment]
Thank you <3

**Pull request merged**
