### PR TITLE
feat: Reduce binary size with more compact exhaustiveness error repor…

### PR DESCRIPTION
**Pull request by jacereda**
…ting

### CODE REVIEW

**Comment by eriksvedang** [comment]
Can you please elaborate on how this reduces binary size? (honest question)

Cheers!

**Comment by jacereda** [comment]
Each distinct string literal with the form "Unhandled case in ...<file/line/col info>" is embedded in the binary. This replaces those strings with a constant string (the format string) which happens to be the same in all cases plus and will be hopefully present only once in the binary, plus some formatting code that will hopefully be smaller than the string it replaces.

**Comment by jacereda** [comment]
Sizes for `test/result.carp` with `-O2 -flto':

Before:
```
   text	   data	    bss	    dec	    hex	filename
  34320	    984	     80	  35384	   8a38	out/Untitled
```

After:
```
    text	   data	    bss	    dec	    hex	filename
  33624	    976	     72	  34672	   8770	out/Untitled
```

Of course, the real win would be to have exhastiveness checks, but while that arrives it might be a good thing.

**Comment by jacereda** [comment]
Also, if we wrap the UNHANDLED macro with `#ifndef UNHANDLED`, someone really concerned about code size could just replace that with a single `abort` call adding a define to `profile.carp`.

**Comment by hellerve** [comment]
The `ifndef` wrap is not added yet; should we do that in a separate PR? It seems like a worthy addition.

**Comment by jacereda** [comment]
An option not requiring the `ifndef`: Just include a header doing:

```
#undef UNHANDLED
#define UNHANDLED(f,l) abort()
```

**Pull request merged**
