### PR TITLE
Compile with -Wall.

### PR DESCRIPTION
**Pull request by jacereda**
This builds on top of #1009 

I'll try to address different warning types one by one to see how far we get.

### CODE REVIEW

**Comment by jacereda** [comment]
The remaining warnings will probably be more invasive. I guess it'll be better to tackle those after the low hanging fruit is in place.

**Comment by jacereda** [comment]
The first relevant commit in this branch is `Prepare for -Wall`.

**Comment by eriksvedang** [comment]
Very nice! Seems like it got a little confused after merge:ing #1009.

**Comment by jacereda** [comment]
Rebased.

**Comment by jacereda** [comment]
Looks like the Nixpkgs workflow is using the unstable channel and `SDL-mixer` was broken on that channel. Let's try with the stable channel.

**Review by hellerve — APPROVED** [review]
Fantastic! So many less code smells!

**Comment by eriksvedang** [comment]
Feels good.

**Pull request merged**
