### PR TITLE
Add copy-filter and rename filter to endo-filter

### PR DESCRIPTION
**Pull request by hellerve**
This PR does the work we discussed in #317. It also adds a check to `endo-filter` that resizes the array if appropriate.

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
I think this looks great!
One comment before merging, the function `templateShrinkCheck` takes an unused argument, perhaps fix that first?

**Comment by eriksvedang** [comment]
Excellent. I think a test in `memory.carp` that triggers the shrinking would be good.

**Comment by hellerve** [comment]
Should I add this or do you want to?

**Comment by eriksvedang** [comment]
If you have the time to do it, please go ahead! I might add some more tests for it later, if I can think of something that might break it...

**Pull request merged**
