### PR TITLE
Added Test module

### PR DESCRIPTION
**Pull request by hellerve**
This PR introduces a whole lot of stuff, most notably a test module. This is a WIP, and I’d advise against merging it at this time. It is, however, in a state in which we should be starting a conversation about it.

Introduced by this PR:
- `=` and `/=` for `Bool`
- `/=` for `Int`
- `/=` for `String`
- `from-chars` for `String`: makes a string from an array of characters (can be removed, not necessary for this PR)
- `repeat` for `String`: repeats a given string `n` times
- `string-join`: append multiple strings (TODO: naming)
- introduce the testing library

What do y’all think?

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
Looks very nice! I'll play around with it a bit and see if I have any comments.

**Comment by eriksvedang** [comment]
The functions on line 50 and 51 in 'prelude.h' must return bool to work on my system:

```
bool Int__EQ_(x, y)     { return x == y; }
bool Int__DIV__EQ_(x, y) { return x != y; }
```

**Comment by hellerve** [comment]
Makes sense. Seems your compiler is pickier than mine!

**Comment by hellerve** [comment]
I fixed the return type for the comparison functions. They were all wrong, I suppose that was just historical baggage. It only turns up when using it in a higher-order fashion, though.

**Pull request merged**
