### PR TITLE
Minimal readline support in REPL

### PR DESCRIPTION
**Pull request by kmate**
Allows to move in the input line with cursors and also keeps an in-process history. Not perfect, but it helps a lot, especially typing up arrow to repeat the last command.

### CODE REVIEW

**Comment by eriksvedang** [comment]
Cool! I've been using rlwrap for this but a more integrated solution is obviously much better in the long run. I'll merge after the weekend when I'm back at my big computer. Thanks!!!

**Comment by eriksvedang** [comment]
Seems like this package adds a dependency for the "readline" command line tool. Do you know if this utility exists on Windows?

**Comment by kmate** [comment]
Well, there is something among the [GNUWin packages](http://gnuwin32.sourceforge.net/packages/readline.htm).

**Comment by hellerve** [comment]
I’d suggest using [Haskeline](https://hackage.haskell.org/package/haskeline) instead, which is a Haskell implementation of editline. That makes it a little more portable, but its interface is a little different. I’ve used it before and could aid in the process of shifting this over to Haskeline if desired.

**Comment by eriksvedang** [comment]
That's an excellent idea, let's do that instead!

**Pull request closed without merging**
