### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by eriksvedang** [comment]
This looks great! But I get an error in the test suite:

```
./test/array.carp

I can’t find any implementation for the interface `/=` of type (λ [&Double, &Double] Bool) at line 103, column 18 in "Array.carp"
```

**Comment by jacereda** [comment]
Is it worth having a `/=` interface? The C compiler will probably be smart enough to do the right thing anyways, or am I missing something?

**Comment by jacereda** [comment]
I mean, could we just implement `/=` as a generic function negating `=`?

**Comment by jacereda** [comment]
Wow, the C compiler is VERY smart. I changed `/=` to a generic and the following:

```
(Project.config "compiler" "/usr/bin/clang")
(add-cflag " -std=c99 -march=native -O2 -fomit-frame-pointer -fvisibility=hidden -flto")
(defn main []
  (let [x (random)
        y (random)]
    (cond (/= x (the Float y))
          1
          0)))
```

Yields this code:
```
out/Untitled:
(__TEXT,__text) section
_main:
0000000100000f60	movslq	%edi, %rax
0000000100000f63	movq	%rax, _System_args(%rip)
0000000100000f6a	movq	%rsi, 0x9f(%rip)
0000000100000f71	movl	$0x1, %eax
0000000100000f76	retq
```

**Comment by eriksvedang** [comment]
I have a hunch we implemented the `/=` for some Carp type level reason, but I don't remember... (do you have an opinion @hellerve ?)

Just relying on the `=` interface and having a single generic `/=` seems nicer, of course. Though since we can't have a constraint on the generic type variable in its signature it will lead to slightly more confusing errors when using `/=` on a type without a `=` function implemented.

The emitted assembler looks nice and small :)

**Comment by hellerve** [comment]
I think we didn’t do this way back when the compiler was much less stable, especially around generics (I think this was around the time I implemented the testing library, which would’ve been late 2017). The idea was always to go back to a generic I believe.

**Comment by jacereda** [comment]
OK, I'll open a separate PR with the `/=` removal.

**Comment by hellerve** [comment]
Yup, it was PR #90 back in the day. I don’t think we even had `definterface` back then.

**Comment by eriksvedang** [comment]
Getting new errors when running the test suite on this one.

**Comment by jacereda** [comment]
Passes for me on Mac. What's the error?

**Comment by hellerve** [comment]
I can confirm that it runs fine for me as well.

**Comment by eriksvedang** [comment]
In examples/basics.carp:
```
I can’t match the types `&r7` and `r7`.

  a : &&r7
  At line 71, column 13 in '/Users/erik/Projects/Carp/core/Double.carp'

  (defn DoubleRef./= [a b] (/= (copy a) (copy b))) : (λ [&r7, &r9] t2)
  At line 71, column 3 in '/Users/erik/Projects/Carp/core/Double.carp'
```

**Comment by jacereda** [comment]
Wasn't that one fixed by https://github.com/carp-lang/Carp/pull/564/commits/336b43a2af9984acb38a1d91b6f08ae7bad0e03b ?

Maybe you need to pull again?

**Comment by eriksvedang** [comment]
No, I already have that... not sure what's up :/

**Comment by eriksvedang** [comment]
Seems to work when I remove that function definition.

**Comment by eriksvedang** [comment]
I guess it interacted with the other patch that made ´/=` generic.

**Comment by jacereda** [comment]
Yeah, this one is supposed to be applied before the `/=` removal.

**Pull request merged**
