### PR TITLE
Scoring tweaks, fixes #526.

### LINKED ISSUE #526: Wrong declaration order in generated output
The following code:

```
(load "Vector.carp")

(deftype (V f) [v (Vector3 f)])
(deftype (X f) [x (Maybe (V f))])

(defn main []
  (let [x (X.init (the (Maybe (V Float)) (Maybe.Nothing)))]
    0))
```

yields:

```
./out/main.c:445:5: error: unknown type name 'Maybe__V__float'
    Maybe__V__float x;
    ^
1 error generated.
```

because the generated file declares types in the wrong order:

```
...
// Depth 103
typedef struct {
    Maybe__V__float x;
} X__float;
...
// Depth 105
typedef struct {
    union {
    struct {
        V__float member0;
    } Just;
    // Nothing
    };
    char _tag;
} Maybe__V__float;
...
```

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by jacereda** [comment]
I can't provide any rationale on the fix other than the fact that it passes the reproduction in #526 and the test suite.

**Comment by jacereda** [comment]
I think I found another case where this still yields invalid code, I'll try to fix it.

**Comment by jacereda** [comment]
Oh, I think it's OK, it was just another manifestation of https://github.com/carp-lang/Carp/issues/516

**Comment by eriksvedang** [comment]
Thanks for working this out!!!

**Pull request merged**
