### PR TITLE
Separate compilation

### PR DESCRIPTION
**Pull request by Vertmo**
I started working on separate compilation, as described in #889 
My current schemes allow for compiling (non-polymorphic) functions, constants and types present in a library. This generates three files:
* a *.o* file containing the c-compiled object code for the definitions
* a *.h* file containing the c-level definitions to be used by the C compiler
* a *.carpi* file containing an interface used by the compiler when loading the library. All the objects are loaded as `external` or `external-types`, which makes the most sense given that, from the point of view of the user, they are indeed externals defined by the *.o* and *.h* file

This also changes the way `Project.title` can be set, as described in #898 , as I felt that the title should only be set in the main file of a project (in the case of this PR, I set a title for the core library, since I need titles to handle some things during linking).

What am I missing here ? Mostly polymorphic functions and macros, which cant be compiled to C-code. What I plan to do is simply leave them "as-is" in the .carpi file, to be compiled later by the user of the library. This kind of "weaken" the purpose of separate compilation, but I don't see any other way of doing it.

### CODE REVIEW

**Comment by Vertmo** [comment]
Oh yeah I would also require help to find out how to make `stack build` also trigger the compilation of the core library (that is trigger *core/Makefile*). The way I did it previously seemed to trip MacOS CI...

**Comment by jacereda** [comment]
My https://github.com/carp-lang/Carp/pull/900 also fails on the MacOS CI.

**Comment by eriksvedang** [comment]
@Vertmo I can try it out locally on MacOS, should I just run the example or what's a good test?

**Comment by Vertmo** [comment]
Well, according to the CI its building Carp itself that fails. Does it work on your machine ?

**Comment by eriksvedang** [comment]
Right now I'm getting a bunch of merge conflicts when trying it out (might be because I just merged some other PR). I'll be happy to try to compile it after fixing that!

**Comment by eriksvedang** [comment]
Will close to keep things tidy, feel free to open again in the future!

**Pull request closed without merging**
