### PR TITLE
Beautify type variables in error messages.

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by jacereda** [comment]
My probably broken attempt at #558

**Comment by jacereda** [comment]
Do you have any preference on how to break the circular imports?

**Comment by eriksvedang** [comment]
What caused the need for circular imports? Since you seem to have solved it I have a little bit of trouble following? :)

**Comment by jacereda** [comment]
I extracted a `TypeErrorDef` module that is imported from both `TypeError` and `AssignTypes`, but maybe you prefer some other way?

**Comment by eriksvedang** [comment]
This didn't seem to beautify anything that I could see (I tried type errors). How did you test it?

**Comment by jacereda** [comment]
Can't remember the example I used. I tried now with:

```
(load "Vector.carp")
(defn foo []
  (Vector3.add (Vector3.init 1f 1f 1f) (Vector3.init 1.0 1.0 1.0)))
```

And found it's broken , because it turned:

```
I can’t match the types `(Vector3 r4)` and `(Ref (Vector3 r2))` within `(Vector3.add (V ... 1 1))`.

  (Vector3.init 1.0f 1.0f 1.0f) : (Vector3 r4)
  At line 3, column 20 in '/private/tmp/err.carp'

  Expected first argument to 'Vector3.add' : (Ref (Vector3 r2))
  At line 3, column 8 in '/private/tmp/err.carp'
```

Into:

```
./carp.sh -b /tmp/err.carp
I can’t match the types `(Vector3 a)` and `(Ref (Vector3 a))` within `(Vector3.add (V ... 1 1))`.

  (Vector3.init 1.0f 1.0f 1.0f) : a
  At line 3, column 20 in '/private/tmp/err.carp'

  Expected first argument to 'Vector3.add' : (Ref (Vector3 a))
  At line 3, column 8 in '/private/tmp/err.carp'


```

Notice the `: a` in the second report is erasing important info.
I'll try to figure out something more robust.

**Comment by jacereda** [comment]
Now it seems to behave better for that example. I've only addressed `UnificationFailed` for now. 

This is the current error:

```
I can’t match the types `(Maybe c)` and `(Ref (Vector3 b))`. within `(Vector3.add (M ... 1.0))`

  (Maybe.Just (Vector3.init 1.0f 1.0f 1.0f)) : (Maybe c)
  At line 3, column 16 in '/private/tmp/err.carp'

  Expected first argument to 'Vector3.add' : (Ref (Vector3 b))
  At line 3, column 4 in '/private/tmp/err.carp'

```

**Comment by eriksvedang** [comment]
While I think the approach here is a good start, I think we need to rewrite it to make it work with the current code and fix the issues that were found. Thanks for the effort, feel free to submit a new PR if you have the time!

**Pull request closed without merging**
