### PR TITLE
Pattern.substitute sprint src & dest overlap = undefined behavior

### LINKED ISSUE #203: Trim removes whole line on Linux
`String.trim` removes whole line instead of spaces and newlines on Linux

```clojure
goodmind@station ~/test $ cat test.carp 
(use IO)

(defn main []
  (do
    (println &(trim "hello\n"))))
goodmind@station ~/test $ carp -x test.carp 

goodmind@station ~/test $ 
```

Different on Mac OS
```clojure
MacBook-Pro:test goodmind$ cat test.carp
(use IO)

(defn main []
  (do
    (println &(trim "hello\n"))))
MacBook-Pro:test goodmind$ carp -x test.carp
hello
MacBook-Pro:test goodmind$
```

### PR DESCRIPTION
**Pull request by Nananas**
See lines `626-629`. [Related StackOverflow question](https://stackoverflow.com/questions/1973572/can-the-input-and-output-strings-to-sprintf-be-the-same#1973595) 
Should fix #203.

Also, minor formatting.

### CODE REVIEW

**Comment by eriksvedang** [comment]
@hellerve Since you wrote the original code, does this look good to you?

**Comment by hellerve** [comment]
Other than that one style critique that I added, most of this is just benignly criticizing my own style (which is very much fine!), and the fix for UB is of course alright. So I’d give it a :+1: but would request that @Nananas changes the style in a separate commit if he has no objections!

**Comment by Nananas** [comment]
@hellerve I just removed the formatting, as it is unrelated to this fix.

**Comment by hellerve** [comment]
That also works! Thank you for your work on this! I have no further objections :)

**Pull request merged**
