### PR TITLE
Use pkg-config for SDL flags.

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by jacereda** [comment]
Should there be a `add-pkg-flags` macro to invoke `pkg-config`?

**Comment by eriksvedang** [comment]
> Should there be a `add-pkg-flags` function to invoke `pkg-config`?

That sounds like a nice idea, do you want to fix that before I merge your PR:s related to this?

**Comment by eriksvedang** [comment]
Got a conflict here now after merge:ing the other PR.

**Comment by jacereda** [comment]
Rebased on top of master.

**Comment by eriksvedang** [comment]
Thanks!

**Pull request merged**
