### PR TITLE
Int.clamp/pow, random fix, Array.initialize and symbol?

### PR DESCRIPTION
**Pull request by Nananas**
Added clamp to Int too. Fixed random-between floating point exception when lower = upper.
Added Array.initialize, symbol? commands.

Also added pow for integers. This does not use math's `pow` function, as it can be **very** slow in certain cases.

### CODE REVIEW

**Comment by eriksvedang** [comment]
Neat, what exactly does Array.initialize do?

**Comment by Nananas** [comment]
like `repeat` but with the index as argument.

**Comment by eriksvedang** [comment]
Ah, thank you!

**Comment by hellerve** [comment]
I don’t particularly like the name `initialize`. I know this is a stone/glasshouse situation, because I suck at naming, but `initialize` isn’t completely intuitive for me. Any reasons it’s called that? Are there other languages that do that?

**Comment by hellerve** [comment]
Also, it’s very similar to a constrained `range`, i.e. `(range 0 n)`.

**Comment by Nananas** [comment]
@hellerve as far as I know, OCaml with `init` and Elm `initialize`. 
Any suggestions?

**Comment by hellerve** [comment]
Ah, I though of `replicate`, not `repeat`. This makes more sense!

**Comment by Nananas** [comment]
I renamed `initialize` to `repeat-indexed`. Naming is not necessarily final though.

I also made `cons` work for lisp arrays.

**Pull request merged**
