### PR TITLE
use MD4C C-library to convert Markdown to html

### PR DESCRIPTION
**Pull request by guberathome**
* removes the python library for conversion of markdown to html
* needs PR #1257 to work

### CODE REVIEW

**Comment by eriksvedang** [comment]
Very cool!

**Comment by guberathome** [comment]
In principle, yes. Quite.
The pattern matching still seems to be broke though...

**Comment by eriksvedang** [comment]
> In principle, yes. Quite.
> The pattern matching still seems to be broke though...

OK, what's the current bug?

**Comment by guberathome** [comment]
The idea is to match all markdown-references 
(with groups for the description an URl).

This works:
```
...:~/contrib_ghub/Carp/docs$ python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
...
>>> finput = open("Memory.md","r")
>>> content = finput.read()
>>> import re
>>> pat = re.compile("\[(.*?)\]\((.*?)\)")      
>>> re.findall(pat, content)
[('Drop', 'Drop.md'), ('Rust', 'https://www.rust-lang.org')]
>>> 
>>> pat2 = re.compile("\[.*?\]\(.*?\)") 
>>> re.findall(pat2, content)
['[Drop](Drop.md)', '[Rust](https://www.rust-lang.org)']
```

However the Pattern-lib match is too greedy:
```
...:~/contrib_ghub/Carp/docs$ carp
Welcome to Carp 0.5.1
> (Pattern.find-all   #"\[.-\]\(.-\)" &(Result.from-success  (IO.read-file "Memory.md") @""))
[58 608 2776]
> (Pattern.match-from    #"\[.-\]\(.-\)" &(Result.from-success  (IO.read-file "Memory.md") @"") 0)
(MatchResult start=58 end=73)
> (Pattern.match-from    #"\[.-\]\(.-\)" &(Result.from-success  (IO.read-file "Memory.md") @"") 74)
(MatchResult start=608 end=2319)
> (Pattern.match-from    #"\[.-\]\(.-\)" &(Result.from-success  (IO.read-file "Memory.md") @"") 2320)
(MatchResult start=2776 end=5477)
```

This might even be technically correct, but it's not what I want.

**Comment by eriksvedang** [comment]
I'll close this for now – please reopen if you want to keep working on it @guberathome !

**Pull request closed without merging**
