### PR TITLE
Travis running run_carp_tests.sh

### PR DESCRIPTION
**Pull request by mkfifo**
This merges in two other PRs #229 and 228

### CODE REVIEW

**Comment by mkfifo** [comment]
This is currently passing on Travis OSX and failing on Travis Linux due to differences in trailing newlines.

It is working on my Linux workstation though.

https://travis-ci.org/mkfifo/Carp/jobs/380981853#L568

**Comment by mkfifo** [comment]
Just testing why this is, do not land yet

**Comment by mkfifo** [comment]
Okay this is now passing on
https://travis-ci.org/mkfifo/Carp/builds/380985710

The underlying issue is due to a change in travis runtime environment which they are not prioritising a fix for
https://github.com/travis-ci/travis-ci/issues/9033

I had to switch our linux environments to use the older travis infrastructure, so our linux test times have gone from 1 minute to 12 minutes.

The only other option I can see is to disable our use of leak sanitizer, but I think 12 minutes is 'okay'.

This is now ready to land if you are happy with it,.

**Comment by eriksvedang** [comment]
What was needed from the older travis infrastructure?

**Comment by mkfifo** [comment]
@eriksvedang the older linux travis infrastructure allows us to use leak sanitizer, the newer linux travis infrastructure under linux won't let it run at all (due to the recent travis-ci/travis-ci#9033)

**Comment by eriksvedang** [comment]
I'll wait with merge:ing this until we have the new Random module so that we can keep those examples.

**Comment by mkfifo** [comment]
@eriksvedang we can merge this in so we get better travis testing now, and then add those tests back in easily enough

**Comment by eriksvedang** [comment]
Fair enough, I'll add a comment in `updating.carp` about brining back the old code later.

**Pull request merged**
