### PR TITLE
feat: Adds Dynamic.sort & improves output of failing dynamic tests

### PR DESCRIPTION
**Pull request by TimDeve**
This adds Dynamic.sort function based on the quicksort described [here](http://learnyouahaskell.com/recursion).

It also contains a refactor of the dynamic test handles to properly display a diff of the expected Vs actual value rather than displaying "true" : "false".

Test display examples:

old:
```
Test 'Dynamic.sort sorts from higher to lower' failed:
        Expected value: 'true', actual value: 'false'
```

new:
```
Test 'Dynamic.sort sorts from higher to lower' failed:
        Expected value: '(4 3 3 5 1)', actual value: '(4 3 3 2 1)'
```

### CODE REVIEW

**Comment by TimDeve** [comment]
`str` for map is a bit odd, my understanding is there is a separate function for dynamic Maps (Dynamic.Map.str), is it not possible to make the standard `str` Map aware? Is it because Maps are just lists of tuples?

**Comment by eriksvedang** [comment]
@TimDeve Yeah there has been some discussions about that, but since the idea is to replace the dynamic map with a faster, built-in one I think we decided to just wait for that instead.

**Comment by hellerve** [comment]
Oh is that the idea? I didn’t know! Bummer, I was hoping we’d move more code out of Haskell and into Carp rather than the other way around.

**Comment by TimDeve** [comment]
I wasn't quite sure if having this in "userspace" was the goal or a shortcut. If we want to keep in Carp I'm wondering if we could "tag" the list with a symbol to be able to tell the difference between a simple list and a map.

**Comment by hellerve** [comment]
> I wasn't quite sure if having this in "userspace" was the goal or a shortcut. If we want to keep in Carp I'm wondering if we could "tag" the list with a symbol to be able to tell the difference between a simple list and a map.

We tried this in #1177 but it was shot down for now.

**Comment by scolsen** [comment]
> #1177

Maybe we can revisit this now, if you're up for it? 

I still think it's a good idea. Having more specialized data structures available in dynamics is a win imo. As I said in that PR thread I think the only thing I'd want is to make sure it's clear in the code when a type is dynamic vs. when it's static.

**Comment by eriksvedang** [comment]
> Also I think it's orthogonal to the dictionary issue. If Haskell based dicts are significantly faster it makes sense to me to use them, but I think dynamic types would still be a useful feature aside from that.

Yeah, agreed.

**Comment by TimDeve** [comment]
> > I wasn't quite sure if having this in "userspace" was the goal or a shortcut. If we want to keep in Carp I'm wondering if we could "tag" the list with a symbol to be able to tell the difference between a simple list and a map.
> 
> We tried this in #1177 but it was shot down for now.

I meant more to have a marker at the front of the list rather than proper dynamic types so `{1 2}` would be:

```clojure
('dynamic-map-marker () () () () () () () () () () () () () () () ((100000000000000000 2)))
```

compared to the current:

```clojure
(() () () () () () () () () () () () () () () ((100000000000000000 2)))
```

**Comment by TimDeve** [comment]
It's ready to merge if people are okay with the changes.

**Review by eriksvedang — APPROVED** [review]
Great!

**Pull request merged**
