### PR TITLE
feat: register MAX and MIN macros for stdint types

### PR DESCRIPTION
**Pull request by scolsen**
Adds MAX and MIN for each INT<N> type and MAX for each UINT<N> type.
These are macros defined by stdint.h and are sometimes useful for bounds
determinations and conversions and such.

### CODE REVIEW

**Review by eriksvedang — APPROVED** [review]
Looks good! Should these be interfaces?

**Comment by scolsen** [comment]
> Looks good! Should these be interfaces?

Good point! They probably should since we have MAXes for the other integer types too. I can make the change.

**Comment by scolsen** [comment]
Added interfaces!

**Comment by scolsen** [comment]
so it turns out these interfaces are breaking tests because our interface resolution doesn't currently overwrites symbol lookup modes! I've got a fix.

**Comment by scolsen** [comment]
Once #1415 merges the tests will pass again and we can merge this.

**Pull request merged**
