### PR TITLE
feat: add fstr

### PR DESCRIPTION
**Pull request by hellerve**
This PR deals with #1115, at least partially. As proposed by  @scolsen, I changed the name to `fstr`.

Cheers

### CODE REVIEW

**Comment by TimDeve** [comment]
Looking good. 

I like that we're holding off on the reader macro for now, maybe we should wait till we're closer to 1.0 so we don't end up with symbols overload ^^

**Comment by hellerve** [comment]
Sounds good. We’ve been adding a lot of features lately, and I think it’s good to not add them in a way that interferes with other goals we might have.

I don’t think we have comprehensive docs on `fmt` or `fstr`? I could add them as part of this PR if that’s desired? If so, should they get their own document?

**Comment by TimDeve** [comment]
I think it would be useful, especially outlining the fact that curly braces shouldn't be used inside other curly braces. How hard would it be to make the macro fail with a readable error if people open new curlies?

**Comment by hellerve** [comment]
The problem is that you need to build a parser for that (because `{` could also show up in a string inside the fstring, for instance), and it gets way more complicated than what I built very quickly.

**Comment by TimDeve** [comment]
Just think we should document the limitations just so people are not confused by the error messages:
```
鲤 (fstr "Hello {{@"a" 2}}")
fstr expected 1 arguments, but received 3.
```

**Comment by hellerve** [comment]
> Just think we should document the limitations just so people are not confused by the error messages:
> 
> ```
> 鲤 (fstr "Hello {{@"a" 2}}")
> fstr expected 1 arguments, but received 3.
> ```

This is actually a Carp parser thing, since you’re closing the string with the second quote, so the thing gets parsed as `(fstr "Hello {{@" a " 2}}")`. As in any string you’ll have  to escape the quotes.

**Comment by hellerve** [comment]
But, of course, the code is still problematic. I’ll add documentation about the limitations of `fstr`.

**Comment by TimDeve** [comment]
Ah yes you're right. A better example:
```
鲤 (fstr "Hello {{1 1}}")
"command:parse" (line 1, column 5):
unexpected end of input
expecting "&", "~", "@", "'", "`", "%@", "%", "(", "$[", "[", "{", "-", digit, "0b", "0x", "#\"", "r\"", "\"", "\\", letter or "}" at dummy-file:0:0.
```

**Comment by hellerve** [comment]
I added a parser for format expression that eliminates the problems pointed out by @TimDeve. To make it work, I also had to add the  following:

* `Dynamic./=`
* `Dynamic.String.head`
* And I had to teach the parser and emitter how to properly deal with escape codes in strings.

**Comment by TimDeve** [comment]
I like the doc, should there be a link to it in the language guide?

**Comment by hellerve** [comment]
I guess; maybe also for quasiquotation and `derive`?

**Comment by TimDeve** [comment]
Should we have a "related page" section like on the [compiler manual page](https://github.com/carp-lang/Carp/blob/master/docs/Manual.md)?

**Comment by hellerve** [comment]
Sounds good! I would avoid making the scope of this PR creep even more and instead add another PR that creates that section. How does that sounds?

**Comment by eriksvedang** [comment]
Lots of good stuff in this PR now :)

**Pull request merged**
