### PR TITLE
Add test script recording and checking

### PR DESCRIPTION
**Pull request by hellerve**
This PR introduces the system described in #216, pretty much as @mkfifo described.

*It also fixes a bug in `System.args` and `noCore`, in that the variable `System.args` is not available when we do not use `core`. This is reasonable I think(?). The tests were broken otherwise.*

The script `test/record.sh` takes in a file path, compiles and runs the file, and records the output in an appropriate file. The other script `test/check.sh` will do the same and diff the outputs. If it fails, it prints an error message and returns 1.

Cheers

### CODE REVIEW

**Comment by eriksvedang** [comment]
Looks good, though it's a bit hard for me to judge since it fails immediately with:
```
./examples/basics.carp failed.
```
I think the error reporting must be improved.

**Comment by hellerve** [comment]
Whoops. This is bad. Usually it should print the diff between the two before exiting.

**Comment by eriksvedang** [comment]
One more thing, the .actual files should be ignored by git, right?

**Comment by hellerve** [comment]
Actually, if the test doesn’t fail, it should remove the `.actual` files, so them remaining in the repo is a smell that something went wrong. Failing tests don’t remove their output, because you might want to inspect them for debugging. But once all tests run fine, you shouldn’t have any of those files anymore.

I’ll probably not be able to fix your comments very soon (as tomorrow I’m 💍 )! If anyone wants to go ahead and take this up, that’d be great. Otherwise I’ll be available again in a while.

**Comment by eriksvedang** [comment]
Ah, I see – that sounds good.

**Pull request merged**
